compliance_settings:
  required_controls:
    - AC-2  # Account Management
    - SC-13 # Cryptographic Key Establishment
  reporting_frequency: "monthly"
  logging_enabled: true
  audit_log_location: "/var/log/compliance_audit.log"
